name: java-maven
on: 
  push:
  pull_request:
    types: [opened, synchronize]
    branches: 
      - main
  workflow_dispatch:
  
jobs: 
  my_first_job:
    runs-on: ubuntu-latest
    
    steps:
    
    - name: Setup Java JDK 11
      uses: actions/setup-java@v1.4.4
      with:
        java-version: 11
        
    - name: Show Java version
      run: "java -version"
      
    - name: Check out code
      uses: actions/checkout@v3

    - name: Show directory
      run: 'pwd'
      
    - name: List Files
      run: 'ls -al'
      
    - name: Install Dependencies
      run: 'mvn compile'
      
    - name: Build Application
      run: 'mvn package -DskipTests'
      
    - name: Test Application
      run: 'mvn test'
